const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const appName = process.argv[2];

if (!appName) {
  console.error(
    "Please provide an app name: node scripts/create-app.js <app-name>"
  );
  process.exit(1);
}

const rootDir = path.join(__dirname, "..");
const appsDir = path.join(rootDir, "apps");
const targetDir = path.join(appsDir, appName);
const packageName = `holi-${appName}`;
const projectName = `${appName}-holi`; // Cloudflare project name
const domainName = `${appName}.holi.tools`;

if (fs.existsSync(targetDir)) {
  console.error(`App ${appName} already exists at ${targetDir}`);
  process.exit(1);
}

console.log(`Creating app: ${appName} in ${targetDir}`);
fs.mkdirSync(targetDir, { recursive: true });
fs.mkdirSync(path.join(targetDir, "src", "pages"), { recursive: true });

// 1. Create package.json
const packageJson = {
  name: packageName,
  type: "module",
  version: "0.0.1",
  scripts: {
    dev: "astro dev",
    start: "astro dev",
    build: "astro build",
    preview: "astro preview",
    astro: "astro",
  },
  dependencies: {
    astro: "^4.0.0",
    "@astrojs/react": "^3.0.0",
    "@astrojs/tailwind": "^5.0.0",
    "@holi/ui": "workspace:*",
    "@holi/configs": "workspace:*",
    tailwindcss: "^3.4.0",
    react: "^18.2.0",
    "react-dom": "^18.2.0",
  },
};
fs.writeFileSync(
  path.join(targetDir, "package.json"),
  JSON.stringify(packageJson, null, 2)
);

// 2. Create astro.config.mjs
const astroConfig = `import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import react from '@astrojs/react';

export default defineConfig({
  integrations: [tailwind({
    applyBaseStyles: false,
  }), react()],
});
`;
fs.writeFileSync(path.join(targetDir, "astro.config.mjs"), astroConfig);

// 3. Create tailwind.config.mjs
const tailwindConfig = `/** @type {import('tailwindcss').Config} */
import sharedConfig from "@holi/configs/tailwind.config";

export default {
  ...sharedConfig,
  content: [
    ...sharedConfig.content,
    "./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"
  ],
};
`;
fs.writeFileSync(path.join(targetDir, "tailwind.config.mjs"), tailwindConfig);

// 4. Create src/pages/index.astro
const indexAstro = `---
---
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<title>${appName} - Holi.tools</title>
	</head>
	<body class="bg-background text-foreground min-h-screen flex items-center justify-center">
		<div class="text-center">
      <h1 class="text-4xl font-bold mb-4">${appName}</h1>
      <p class="text-muted-foreground">Generated by Holi.tools CLI</p>
    </div>
	</body>
</html>
`;
fs.writeFileSync(path.join(targetDir, "src/pages/index.astro"), indexAstro);

// 5. Create about.md
const aboutMd = `# About ${appName}

This tool was automatically generated as part of the Holi.tools ecosystem.

## Purpose
- Describe the purpose of ${appName} here.

## Tech Stack
- Astro
- Tailwind CSS via @holi/configs
- Components via @holi/ui
`;
fs.writeFileSync(path.join(targetDir, "about.md"), aboutMd);

// 6. Update root package.json with deploy script
const rootPackageJsonPath = path.join(rootDir, "package.json");
const rootPackageJson = require(rootPackageJsonPath);

rootPackageJson.scripts[`deploy:${appName}`] =
  `turbo run build --filter=${packageName} && wrangler pages deploy ./apps/${appName}/dist --project-name ${projectName}`;

fs.writeFileSync(rootPackageJsonPath, JSON.stringify(rootPackageJson, null, 2));

console.log(`App ${appName} created successfully!`);
console.log(`Added script: deploy:${appName}`);
console.log(`To deploy run: pnpm run deploy:${appName}`);
console.log(
  `NOTE: You may need to create the Cloudflare project manually via: npx wrangler pages project create ${projectName} --production-branch main`
);
